/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CancellationsIndexRouteImport } from './routes/cancellations/index'
import { Route as AllocationCheckerIndexRouteImport } from './routes/allocation-checker/index'
import { Route as ApiMegaethRouteImport } from './routes/api/megaeth'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationsIndexRoute = CancellationsIndexRouteImport.update({
  id: '/cancellations/',
  path: '/cancellations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationCheckerIndexRoute = AllocationCheckerIndexRouteImport.update({
  id: '/allocation-checker/',
  path: '/allocation-checker/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMegaethRoute = ApiMegaethRouteImport.update({
  id: '/api/megaeth',
  path: '/api/megaeth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/megaeth': typeof ApiMegaethRoute
  '/allocation-checker': typeof AllocationCheckerIndexRoute
  '/cancellations': typeof CancellationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/megaeth': typeof ApiMegaethRoute
  '/allocation-checker': typeof AllocationCheckerIndexRoute
  '/cancellations': typeof CancellationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/megaeth': typeof ApiMegaethRoute
  '/allocation-checker/': typeof AllocationCheckerIndexRoute
  '/cancellations/': typeof CancellationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/graphql'
    | '/api/megaeth'
    | '/allocation-checker'
    | '/cancellations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/graphql'
    | '/api/megaeth'
    | '/allocation-checker'
    | '/cancellations'
  id:
    | '__root__'
    | '/'
    | '/api/graphql'
    | '/api/megaeth'
    | '/allocation-checker/'
    | '/cancellations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiMegaethRoute: typeof ApiMegaethRoute
  AllocationCheckerIndexRoute: typeof AllocationCheckerIndexRoute
  CancellationsIndexRoute: typeof CancellationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellations/': {
      id: '/cancellations/'
      path: '/cancellations'
      fullPath: '/cancellations'
      preLoaderRoute: typeof CancellationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation-checker/': {
      id: '/allocation-checker/'
      path: '/allocation-checker'
      fullPath: '/allocation-checker'
      preLoaderRoute: typeof AllocationCheckerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/megaeth': {
      id: '/api/megaeth'
      path: '/api/megaeth'
      fullPath: '/api/megaeth'
      preLoaderRoute: typeof ApiMegaethRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiMegaethRoute: ApiMegaethRoute,
  AllocationCheckerIndexRoute: AllocationCheckerIndexRoute,
  CancellationsIndexRoute: CancellationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
