/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationCheckerIndexRouteImport } from './routes/allocation-checker/index'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationCheckerIndexRoute = AllocationCheckerIndexRouteImport.update({
  id: '/allocation-checker/',
  path: '/allocation-checker/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/allocation-checker': typeof AllocationCheckerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/allocation-checker': typeof AllocationCheckerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/allocation-checker/': typeof AllocationCheckerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/graphql' | '/allocation-checker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/graphql' | '/allocation-checker'
  id: '__root__' | '/' | '/api/graphql' | '/allocation-checker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  AllocationCheckerIndexRoute: typeof AllocationCheckerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation-checker/': {
      id: '/allocation-checker/'
      path: '/allocation-checker'
      fullPath: '/allocation-checker'
      preLoaderRoute: typeof AllocationCheckerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  AllocationCheckerIndexRoute: AllocationCheckerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
